
import { FC } from "react";
import {
  RiFileList3Line,
 
  RiShieldKeyholeLine,
  RiUserHeartLine,
  RiMoneyDollarCircleLine,
  RiShieldCheckLine,
  RiBrainLine,
  RiFileShield2Line,
  RiScales2Line,
} from "react-icons/ri";

import AgreementSignatures from "./AgreementSignatures";

const AgreementPage: FC = () => {
  return (
    <main className="max-w-7xl mx-auto px-6 py-12">
      {/* Signature Block */}

      {/* 1. Purpose of Agreement */}
      <section
        className="
    bg-[#00A9FF1A]
    rounded-xl
    border
    gradient-border
    p-8
    mb-8
    shadow-[inset_0_4px_12px_0px_#2255FE4D]
  "
      >
        <h2 className="text-2xl font-bold text-white mb-6 flex items-center">
          <div className="w-8 h-8 bg-gray-500 rounded-lg flex justify-center items-center mr-3">
            <RiFileList3Line className="text-black text-sm" />
          </div>
          1. Purpose of Agreement
        </h2>

        <p className="text-gray-300 leading-relaxed">
          The Company recognizes the Developer as a core contributor to
          VoltSec.io’s technological development and grants the following rights
          and responsibilities.
        </p>
      </section>

      {/* 2. Lifetime Profit Share */}
      <section
        className="
    bg-[#00A9FF1A]
    rounded-xl
    border
    gradient-border
    p-8
    mb-8
    shadow-[inset_0_4px_12px_0px_#2255FE4D]
  "
      >
        <h2 className="text-2xl font-bold text-white mb-6 flex items-center">
          <div className="w-8 h-8 bg-gray-500 rounded-lg flex justify-center items-center mr-3">
            <RiMoneyDollarCircleLine className="text-black text-sm" />
          </div>
          2. Lifetime Profit-Share
        </h2>

        <ul className="space-y-3 text-gray-300">
          <li>
            1. The Company shall pay the Developer{" "}
            <b className="text-white">
              10% of the net profit generated by VoltSec.io.
            </b>
          </li>
          <li>
            2. This profit-share is{" "}
            <b className="text-white">lifetime, irrevocable</b>, and
            <b> does not end </b> if the Developer:
            <ul className="list-disc ml-6 mt-2 text-gray-400">
              <li>Resigns</li>
              <li>Joins another company</li>
              <li>Becomes inactive</li>
              <li>Retires</li>
              <li>Becomes permanently disabled</li>
            </ul>
          </li>
          <li>
            3. Profit-share will be paid <b>quarterly</b>, along with a profit
            statement
          </li>
        </ul>
      </section>

      {/* 3. Family Succession Clause */}
      <section
        className="
    bg-[#00A9FF1A]
    rounded-xl
    border
    gradient-border
    p-8
    mb-8
    shadow-[inset_0_4px_12px_0px_#2255FE4D]
  "
      >
        <h2 className="text-2xl font-bold text-white mb-6 flex items-center">
          <div className="w-8 h-8 bg-gray-500 rounded-lg flex justify-center items-center mr-3">
            <RiUserHeartLine className="text-black text-sm" />
          </div>
          3. Family Succession Clause
        </h2>

        <ul className="space-y-3 text-gray-300">
          <li>
            1. In the event of the Developer’s death,{" "}
            <b className="text-white">5% of VoltSec.io’s net profit</b> will be
            paid to:
            <ul className="list-disc ml-6 mt-2 text-gray-400">
              <li>The Developer’s legal heir(s), OR</li>
              <li>A nominee specified by the Developer</li>
            </ul>
          </li>
          <li>
            2. This family profit-share continues <b>indefinitely</b>, as long
            as VoltSec.io generates revenue.
          </li>
        </ul>
      </section>

      {/* 4. NDA */}
      <section
        className="
    bg-[#00A9FF1A]
    rounded-xl
    border
    gradient-border
    p-8
    mb-8
    shadow-[inset_0_4px_12px_0px_#2255FE4D]
  "
      >
        <h2 className="text-2xl font-bold text-white mb-6 flex items-center">
          <div className="w-8 h-8 bg-gray-500 rounded-lg flex justify-center items-center mr-3">
            <RiShieldKeyholeLine className="text-black text-sm" />
          </div>
          4. Non-Disclosure Agreement (NDA)
        </h2>

        <p className="text-gray-300 mb-4">The Developer agrees:</p>

        <ol className="list-decimal ml-6 text-gray-300 space-y-3">
          <li>
            <b>Not to disclose </b>
            any information, documents, code, architecture, models, business
            strategy, technical operations, or internal processes of VoltSec.io
            to any third party.
          </li>

          <li>
            Confidential information includes, but is not limited to:
            <ul className="list-disc ml-6 text-gray-400 space-y-2 mt-2">
              <li>AI/Deep Learning models</li>
              <li>Scanning algorithms</li>
              <li>Source code & repositories</li>
              <li>Business logic & architecture</li>
              <li>Client data</li>
              <li>Internal tools & dashboards</li>
            </ul>
          </li>
          <li>
            This NDA is <b>permanent</b> and remains valid even after:
            <ul className="list-disc ml-6 text-gray-400 space-y-2 mt-2">
              <li>Job termination</li>
              <li>Resignation</li>
              <li>Retirement</li>
              <li>Death</li>
            </ul>
          </li>
        </ol>

        <p className="text-gray-300 mt-6">
          Any breach will make the Developer legally and financially liable.
        </p>
      </section>

      {/* 5. Non-Compete */}
      <section
        className="
    bg-[#00A9FF1A]
    rounded-xl
    border
    gradient-border
    p-8
    mb-8
    shadow-[inset_0_4px_12px_0px_#2255FE4D]
  "
      >
        <h2 className="text-2xl font-bold text-white mb-6 flex items-center">
          <div className="w-8 h-8 bg-gray-500 rounded-lg flex justify-center items-center mr-3">
            <RiShieldCheckLine className="text-black text-sm" />
          </div>
          5. Non-Compete Clause
        </h2>

        <p className="text-gray-300 mb-4">The Developer agrees:</p>

        <ol className="list-decimal ml-6 text-gray-300 space-y-3">
          <li>
            Not to <b>create, replicate, assist, or contribute </b> to any
            product, company, or individual building:
            <ul className="list-disc ml-6 text-gray-400 space-y-2 mt-2">
              <li>A similar cybersecurity AI platform</li>
              <li>A competitor to VoltSec.io</li>
              <li>
                A tool that copies VoltSec.io’s architecture, features, or code
              </li>
            </ul>
          </li>

          <li>
            This restriction lasts
            <b className="text-white"> 10 years </b>
            from the date of exit from active development.
          </li>
        </ol>
      </section>

      {/* 6. IP Ownership */}
      <section
        className="
    bg-[#00A9FF1A]
    rounded-xl
    border
    gradient-border
    p-8
    mb-8
    shadow-[inset_0_4px_12px_0px_#2255FE4D]
  "
      >
        <h2 className="text-2xl font-bold text-white mb-6 flex items-center">
          <div className="w-8 h-8 bg-gray-500 rounded-lg flex justify-center items-center mr-3">
            <RiBrainLine className="text-black text-sm" />
          </div>
          6. Intellectual Property (IP) Ownership
        </h2>

        <ol className="list-decimal ml-6 text-gray-300 space-y-3">
          <li>
            All code, models, tools, architecture, designs, and systems
            developed for VoltSec.io{" "}
            <b> belong solely to VoltSec.io and The RD Group of Industries.</b>
          </li>

          <li>
            The Developer shall have no ownership over IP created during or
            after their tenure.
          </li>
        </ol>
      </section>

      {/* 7. Termination */}
      <section
        className="
    bg-[#00A9FF1A]
    rounded-xl
    border
    gradient-border
    p-8
    mb-8
    shadow-[inset_0_4px_12px_0px_#2255FE4D]
  "
      >
        <h2 className="text-2xl font-bold text-white mb-6 flex items-center">
          <div className="w-8 h-8 bg-gray-500 rounded-lg flex justify-center items-center mr-3">
            <RiFileShield2Line className="text-black text-sm" />
          </div>
          7. Termination
        </h2>

        <p className="text-gray-300">
          The Company may terminate active work engagement, but:
        </p>

        <ul className="list-disc ml-6 text-gray-400 mt-2 space-y-2">
          <li>Profit-share rights</li>
          <li>NDA obligations</li>
          <li>Non-compete restrictions</li>
          <li>IP ownership clauses</li>
        </ul>

        <p className="text-gray-300 mt-4">
          <b>remain fully enforceable.</b>
        </p>
      </section>

      {/* 8. Governing Law */}
      <section
        className="
    bg-[#00A9FF1A]
    rounded-xl
    border
    gradient-border
    p-8
    mb-8
    shadow-[inset_0_4px_12px_0px_#2255FE4D]
  "
      >
        <h2 className="text-2xl font-bold text-white mb-6 flex items-center">
          <div className="w-8 h-8 bg-gray-500 rounded-lg flex justify-center items-center mr-3">
            <RiScales2Line className="text-black text-sm" />
          </div>
          8. Governing Law
        </h2>

        <p className="text-gray-300">
          This Agreement will be governed by the laws of India, with
          jurisdiction in the <b className="text-white">Delhi Supreme Court</b>.
        </p>
      </section>
      <AgreementSignatures />
    </main>
  );
};

export default AgreementPage;
